//! The ARM instruction table, generated from GNU binutils 2.47.
//!
//! Do not edit: `tools/tables/arm.py table` writes this file from the
//! disassembler's own tables in `opcodes/arm-dis.c`. [`super::generic`]
//! encodes from it, and the script's doc comment says which instructions
//! are here and which a hand-written encoder owns.

/// Where a value's bits live in the instruction word, from the value's own
/// low bits up: `(lsb, width)` pieces. A 32-bit Thumb instruction is one
/// word with its first halfword on top, which is how `arm-dis.c` numbers
/// the bits too.
pub type Field = &'static [(u8, u8)];

/// Which instruction set a form belongs to, and how wide it is.
#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum Set {
    /// A32, four bytes, with a condition field.
    Arm,
    /// T32, two bytes.
    T16,
    /// T32, four bytes.
    T32,
}

/// One operand of a form, and where its value goes.
#[derive(Copy, Clone, Debug)]
pub enum Op {
    /// A core register: `bits` bits at `lsb`.
    Reg(u8, u8),
    /// A core register whose four bits the encoding holds twice.
    RegTwice(u8, u8),
    /// The second half of a register pair, which must be the register after
    /// the one before it and carries no bits of its own.
    Next,
    /// A base register written `[rn]`.
    Base(u8, u8),
    /// An immediate `#v`, holding `v / scale - bias`.
    Imm(Field, u8, u8),
    /// A trailing `, {imm}`, which may be left out: the coprocessor opcode
    /// of `cdp`, `mcr` and `mrc`, written with or without the braces.
    OptImm(Field),
    /// `nop`'s hint number, which may be left out and needs its braces.
    Hint(Field),
    /// The `#lsb` of a bitfield instruction.
    Lsb(Field),
    /// Its `#width`, held as the most significant bit it reaches.
    Msb(Field),
    /// Its `#width`, held one less.
    Width(Field),
    /// An optional `, ror #8`, `#16` or `#24`, two bits at `lsb`.
    Rotate(u8),
    /// An optional shift: `amount` bits at `lsb`, and a bit that says `asr`
    /// rather than `lsl` -- 255 when only `asr` is allowed, 254 when only
    /// `lsl` is. A second field holds an amount the first cannot.
    SatShift(u8, u8, u8, u8, u8),
    /// A coprocessor number, `p0` to `p15`.
    Coproc(u8),
    /// A coprocessor register, `c0` to `c15`.
    CReg(u8),
    /// A barrier option, `sy` where none is written.
    Barrier,
    /// `APSR_nzcv`, which `mrc` takes in place of a register.
    ApsrNzcv,
    /// `!` on the register before it, the bit at `lsb`.
    Writeback(u8),
    /// The `a`, `i` and `f` letters of `cpsie` and `cpsid`, the `f` bit at
    /// `lsb`.
    IntFlags(u8),
    /// `be` or `le`, the bit at `lsb`.
    Endian(u8),
    /// `[rn, rm]`, or `[rn, rm, lsl #1]` where the third field is 1: the
    /// table branches.
    IdxMem(u8, u8, u8),
    /// `[rn]` or `[rn, #imm]`, the base at the first position and the
    /// offset in the field, scaled.
    OffMem(u8, Field, u8),
    /// The addressing modes of `ldc` and `stc`.
    CoprocMem,
    /// `srs`'s base register, which may be left out and must be `sp`: the
    /// register goes at the first position and the `!` bit at the second.
    SpBase(u8, u8),
}

/// One way of writing one instruction.
pub struct Form {
    pub name: &'static str,
    pub set: Set,
    /// The opcode word, with every fixed bit already in place.
    pub word: u32,
    /// Whether the instruction may carry a condition. An A32 form that may
    /// not has its condition field in `word`.
    pub cond: bool,
    pub ops: &'static [Op],
}

const fn f(name: &'static str, set: Set, word: u32, cond: bool, ops: &'static [Op]) -> Form {
    Form {
        name,
        set,
        word,
        cond,
        ops,
    }
}

/// Mnemonics GNU as takes as another spelling of one in the table.
pub static SPELLINGS: &[(&str, &str)] = &[
    ("rfe", "rfeia"),
    ("rfeea", "rfedb"),
    ("rfeed", "rfeib"),
    ("rfefa", "rfeda"),
    ("rfefd", "rfeia"),
    ("srs", "srsia"),
    ("srsea", "srsia"),
    ("srsed", "srsda"),
    ("srsfa", "srsib"),
    ("srsfd", "srsdb"),
    ("swi", "svc"),
];

/// Every form, sorted by name.
pub static FORMS: &[Form] = &[
    f(
        "bfc",
        Set::T32,
        0xf36f0000,
        true,
        &[
            Op::Reg(8, 4),
            Op::Lsb(&[(6, 2), (12, 3)]),
            Op::Msb(&[(0, 5)]),
        ],
    ),
    f(
        "bfc",
        Set::Arm,
        0x07c0001f,
        true,
        &[Op::Reg(12, 4), Op::Lsb(&[(7, 5)]), Op::Msb(&[(16, 5)])],
    ),
    f(
        "bfi",
        Set::T32,
        0xf3600000,
        true,
        &[
            Op::Reg(8, 4),
            Op::Reg(16, 4),
            Op::Lsb(&[(6, 2), (12, 3)]),
            Op::Msb(&[(0, 5)]),
        ],
    ),
    f(
        "bfi",
        Set::Arm,
        0x07c00010,
        true,
        &[
            Op::Reg(12, 4),
            Op::Reg(0, 4),
            Op::Lsb(&[(7, 5)]),
            Op::Msb(&[(16, 5)]),
        ],
    ),
    f(
        "bkpt",
        Set::T16,
        0x0000be00,
        false,
        &[Op::Imm(&[(0, 8)], 1, 0)],
    ),
    f(
        "bkpt",
        Set::Arm,
        0xe1200070,
        false,
        &[Op::Imm(&[(0, 4), (8, 12)], 1, 0)],
    ),
    f("bxj", Set::T32, 0xf3c08f00, true, &[Op::Reg(16, 4)]),
    f("bxj", Set::Arm, 0x012fff20, true, &[Op::Reg(0, 4)]),
    f(
        "cdp",
        Set::T32,
        0xee000000,
        false,
        &[
            Op::Coproc(8),
            Op::Imm(&[(20, 4)], 1, 0),
            Op::CReg(12),
            Op::CReg(16),
            Op::CReg(0),
            Op::OptImm(&[(5, 3)]),
        ],
    ),
    f(
        "cdp",
        Set::Arm,
        0x0e000000,
        true,
        &[
            Op::Coproc(8),
            Op::Imm(&[(20, 4)], 1, 0),
            Op::CReg(12),
            Op::CReg(16),
            Op::CReg(0),
            Op::OptImm(&[(5, 3)]),
        ],
    ),
    f(
        "cdp2",
        Set::T32,
        0xfe000000,
        false,
        &[
            Op::Coproc(8),
            Op::Imm(&[(20, 4)], 1, 0),
            Op::CReg(12),
            Op::CReg(16),
            Op::CReg(0),
            Op::OptImm(&[(5, 3)]),
        ],
    ),
    f(
        "cdp2",
        Set::Arm,
        0xfe000000,
        true,
        &[
            Op::Coproc(8),
            Op::Imm(&[(20, 4)], 1, 0),
            Op::CReg(12),
            Op::CReg(16),
            Op::CReg(0),
            Op::OptImm(&[(5, 3)]),
        ],
    ),
    f("clrex", Set::T32, 0xf3bf8f2f, true, &[]),
    f("clrex", Set::Arm, 0xf57ff01f, false, &[]),
    f(
        "clz",
        Set::T32,
        0xfab0f080,
        true,
        &[Op::Reg(8, 4), Op::RegTwice(16, 0)],
    ),
    f(
        "clz",
        Set::Arm,
        0x016f0f10,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4)],
    ),
    f(
        "cps",
        Set::T32,
        0xf3af8100,
        false,
        &[Op::Imm(&[(0, 5)], 1, 0)],
    ),
    f(
        "cps",
        Set::Arm,
        0xf1020000,
        false,
        &[Op::Imm(&[(0, 5)], 1, 0)],
    ),
    f("cpsid", Set::T16, 0x0000b670, false, &[Op::IntFlags(0)]),
    f("cpsid", Set::T32, 0xf3af8600, false, &[Op::IntFlags(5)]),
    f(
        "cpsid",
        Set::T32,
        0xf3af8700,
        false,
        &[Op::IntFlags(5), Op::Imm(&[(0, 5)], 1, 0)],
    ),
    f("cpsid", Set::Arm, 0xf10c0000, false, &[Op::IntFlags(6)]),
    f(
        "cpsid",
        Set::Arm,
        0xf10e0000,
        false,
        &[Op::IntFlags(6), Op::Imm(&[(0, 5)], 1, 0)],
    ),
    f("cpsie", Set::T16, 0x0000b660, false, &[Op::IntFlags(0)]),
    f("cpsie", Set::T32, 0xf3af8400, false, &[Op::IntFlags(5)]),
    f(
        "cpsie",
        Set::T32,
        0xf3af8500,
        false,
        &[Op::IntFlags(5), Op::Imm(&[(0, 5)], 1, 0)],
    ),
    f("cpsie", Set::Arm, 0xf1080000, false, &[Op::IntFlags(6)]),
    f(
        "cpsie",
        Set::Arm,
        0xf10a0000,
        false,
        &[Op::IntFlags(6), Op::Imm(&[(0, 5)], 1, 0)],
    ),
    f("csdb", Set::T32, 0xf3af8014, false, &[]),
    f("csdb", Set::Arm, 0xe320f014, false, &[]),
    f(
        "dbg",
        Set::T32,
        0xf3af80f0,
        true,
        &[Op::Imm(&[(0, 4)], 1, 0)],
    ),
    f(
        "dbg",
        Set::Arm,
        0x0320f0f0,
        true,
        &[Op::Imm(&[(0, 4)], 1, 0)],
    ),
    f("dmb", Set::T32, 0xf3bf8f50, true, &[Op::Barrier]),
    f("dmb", Set::Arm, 0xf57ff050, false, &[Op::Barrier]),
    f("dsb", Set::T32, 0xf3bf8f40, true, &[Op::Barrier]),
    f("dsb", Set::Arm, 0xf57ff040, false, &[Op::Barrier]),
    f("eret", Set::Arm, 0x0160006e, true, &[]),
    f(
        "hlt",
        Set::Arm,
        0xe1000070,
        false,
        &[Op::Imm(&[(0, 4), (8, 12)], 1, 0)],
    ),
    f(
        "hvc",
        Set::T32,
        0xf7e08000,
        true,
        &[Op::Imm(&[(0, 12), (16, 4)], 1, 0)],
    ),
    f(
        "hvc",
        Set::Arm,
        0x01400070,
        true,
        &[Op::Imm(&[(0, 4), (8, 12)], 1, 0)],
    ),
    f("isb", Set::T32, 0xf3bf8f60, true, &[Op::Barrier]),
    f("isb", Set::Arm, 0xf57ff060, false, &[Op::Barrier]),
    f(
        "ldc",
        Set::T32,
        0xec100000,
        false,
        &[Op::Coproc(8), Op::CReg(12), Op::CoprocMem],
    ),
    f(
        "ldc",
        Set::Arm,
        0x0c100000,
        true,
        &[Op::Coproc(8), Op::CReg(12), Op::CoprocMem],
    ),
    f(
        "ldc2",
        Set::T32,
        0xfc100000,
        false,
        &[Op::Coproc(8), Op::CReg(12), Op::CoprocMem],
    ),
    f(
        "ldc2",
        Set::Arm,
        0xfc100000,
        true,
        &[Op::Coproc(8), Op::CReg(12), Op::CoprocMem],
    ),
    f(
        "ldc2l",
        Set::T32,
        0xfc500000,
        false,
        &[Op::Coproc(8), Op::CReg(12), Op::CoprocMem],
    ),
    f(
        "ldc2l",
        Set::Arm,
        0xfc500000,
        true,
        &[Op::Coproc(8), Op::CReg(12), Op::CoprocMem],
    ),
    f(
        "ldcl",
        Set::T32,
        0xec500000,
        false,
        &[Op::Coproc(8), Op::CReg(12), Op::CoprocMem],
    ),
    f(
        "ldcl",
        Set::Arm,
        0x0c500000,
        true,
        &[Op::Coproc(8), Op::CReg(12), Op::CoprocMem],
    ),
    f(
        "ldrex",
        Set::T32,
        0xe8500f00,
        true,
        &[Op::Reg(12, 4), Op::Base(16, 4)],
    ),
    f(
        "ldrex",
        Set::T32,
        0xe8500f00,
        true,
        &[Op::Reg(12, 4), Op::OffMem(16, &[(0, 8)], 4)],
    ),
    f(
        "ldrex",
        Set::Arm,
        0x01900f9f,
        true,
        &[Op::Reg(12, 4), Op::Base(16, 4)],
    ),
    f(
        "ldrexb",
        Set::T32,
        0xe8d00f4f,
        true,
        &[Op::Reg(12, 4), Op::Base(16, 4)],
    ),
    f(
        "ldrexb",
        Set::Arm,
        0x01d00f9f,
        true,
        &[Op::Reg(12, 4), Op::Base(16, 4)],
    ),
    f(
        "ldrexd",
        Set::T32,
        0xe8d0007f,
        true,
        &[Op::Reg(12, 4), Op::Reg(8, 4), Op::Base(16, 4)],
    ),
    f(
        "ldrexd",
        Set::Arm,
        0x01b00f9f,
        true,
        &[Op::Reg(12, 4), Op::Next, Op::Base(16, 4)],
    ),
    f(
        "ldrexh",
        Set::T32,
        0xe8d00f5f,
        true,
        &[Op::Reg(12, 4), Op::Base(16, 4)],
    ),
    f(
        "ldrexh",
        Set::Arm,
        0x01f00f9f,
        true,
        &[Op::Reg(12, 4), Op::Base(16, 4)],
    ),
    f(
        "mcr",
        Set::T32,
        0xee000010,
        false,
        &[
            Op::Coproc(8),
            Op::Imm(&[(21, 3)], 1, 0),
            Op::Reg(12, 4),
            Op::CReg(16),
            Op::CReg(0),
            Op::OptImm(&[(5, 3)]),
        ],
    ),
    f(
        "mcr",
        Set::Arm,
        0x0e000010,
        true,
        &[
            Op::Coproc(8),
            Op::Imm(&[(21, 3)], 1, 0),
            Op::Reg(12, 4),
            Op::CReg(16),
            Op::CReg(0),
            Op::OptImm(&[(5, 3)]),
        ],
    ),
    f(
        "mcr2",
        Set::T32,
        0xfe000010,
        false,
        &[
            Op::Coproc(8),
            Op::Imm(&[(21, 3)], 1, 0),
            Op::Reg(12, 4),
            Op::CReg(16),
            Op::CReg(0),
            Op::OptImm(&[(5, 3)]),
        ],
    ),
    f(
        "mcr2",
        Set::Arm,
        0xfe000010,
        true,
        &[
            Op::Coproc(8),
            Op::Imm(&[(21, 3)], 1, 0),
            Op::Reg(12, 4),
            Op::CReg(16),
            Op::CReg(0),
            Op::OptImm(&[(5, 3)]),
        ],
    ),
    f(
        "mcrr",
        Set::T32,
        0xec400000,
        false,
        &[
            Op::Coproc(8),
            Op::Imm(&[(4, 4)], 1, 0),
            Op::Reg(12, 4),
            Op::Reg(16, 4),
            Op::CReg(0),
        ],
    ),
    f(
        "mcrr",
        Set::Arm,
        0x0c400000,
        true,
        &[
            Op::Coproc(8),
            Op::Imm(&[(4, 4)], 1, 0),
            Op::Reg(12, 4),
            Op::Reg(16, 4),
            Op::CReg(0),
        ],
    ),
    f(
        "mcrr2",
        Set::T32,
        0xfc400000,
        false,
        &[
            Op::Coproc(8),
            Op::Imm(&[(4, 4)], 1, 0),
            Op::Reg(12, 4),
            Op::Reg(16, 4),
            Op::CReg(0),
        ],
    ),
    f(
        "mcrr2",
        Set::Arm,
        0xfc400000,
        true,
        &[
            Op::Coproc(8),
            Op::Imm(&[(4, 4)], 1, 0),
            Op::Reg(12, 4),
            Op::Reg(16, 4),
            Op::CReg(0),
        ],
    ),
    f(
        "mrc",
        Set::T32,
        0xee100010,
        false,
        &[
            Op::Coproc(8),
            Op::Imm(&[(21, 3)], 1, 0),
            Op::Reg(12, 4),
            Op::CReg(16),
            Op::CReg(0),
            Op::OptImm(&[(5, 3)]),
        ],
    ),
    f(
        "mrc",
        Set::T32,
        0xee10f010,
        false,
        &[
            Op::Coproc(8),
            Op::Imm(&[(21, 3)], 1, 0),
            Op::ApsrNzcv,
            Op::CReg(16),
            Op::CReg(0),
            Op::OptImm(&[(5, 3)]),
        ],
    ),
    f(
        "mrc",
        Set::Arm,
        0x0e100010,
        true,
        &[
            Op::Coproc(8),
            Op::Imm(&[(21, 3)], 1, 0),
            Op::Reg(12, 4),
            Op::CReg(16),
            Op::CReg(0),
            Op::OptImm(&[(5, 3)]),
        ],
    ),
    f(
        "mrc",
        Set::Arm,
        0x0e10f010,
        true,
        &[
            Op::Coproc(8),
            Op::Imm(&[(21, 3)], 1, 0),
            Op::ApsrNzcv,
            Op::CReg(16),
            Op::CReg(0),
            Op::OptImm(&[(5, 3)]),
        ],
    ),
    f(
        "mrc2",
        Set::T32,
        0xfe100010,
        false,
        &[
            Op::Coproc(8),
            Op::Imm(&[(21, 3)], 1, 0),
            Op::Reg(12, 4),
            Op::CReg(16),
            Op::CReg(0),
            Op::OptImm(&[(5, 3)]),
        ],
    ),
    f(
        "mrc2",
        Set::Arm,
        0xfe100010,
        true,
        &[
            Op::Coproc(8),
            Op::Imm(&[(21, 3)], 1, 0),
            Op::Reg(12, 4),
            Op::CReg(16),
            Op::CReg(0),
            Op::OptImm(&[(5, 3)]),
        ],
    ),
    f(
        "mrrc",
        Set::T32,
        0xec500000,
        false,
        &[
            Op::Coproc(8),
            Op::Imm(&[(4, 4)], 1, 0),
            Op::Reg(12, 4),
            Op::Reg(16, 4),
            Op::CReg(0),
        ],
    ),
    f(
        "mrrc",
        Set::Arm,
        0x0c500000,
        true,
        &[
            Op::Coproc(8),
            Op::Imm(&[(4, 4)], 1, 0),
            Op::Reg(12, 4),
            Op::Reg(16, 4),
            Op::CReg(0),
        ],
    ),
    f(
        "mrrc2",
        Set::T32,
        0xfc500000,
        false,
        &[
            Op::Coproc(8),
            Op::Imm(&[(4, 4)], 1, 0),
            Op::Reg(12, 4),
            Op::Reg(16, 4),
            Op::CReg(0),
        ],
    ),
    f(
        "mrrc2",
        Set::Arm,
        0xfc500000,
        true,
        &[
            Op::Coproc(8),
            Op::Imm(&[(4, 4)], 1, 0),
            Op::Reg(12, 4),
            Op::Reg(16, 4),
            Op::CReg(0),
        ],
    ),
    f("nop", Set::T16, 0x0000bf00, true, &[]),
    f("nop", Set::T32, 0xf3af8000, true, &[]),
    f("nop", Set::Arm, 0x0320f000, true, &[Op::Hint(&[(0, 8)])]),
    f(
        "pkhbt",
        Set::T32,
        0xeac00000,
        true,
        &[
            Op::Reg(8, 4),
            Op::Reg(16, 4),
            Op::Reg(0, 4),
            Op::SatShift(6, 2, 254, 12, 3),
        ],
    ),
    f(
        "pkhbt",
        Set::Arm,
        0x06800010,
        true,
        &[
            Op::Reg(12, 4),
            Op::Reg(16, 4),
            Op::Reg(0, 4),
            Op::SatShift(7, 5, 254, 255, 0),
        ],
    ),
    f(
        "pkhtb",
        Set::T32,
        0xeac00000,
        true,
        &[Op::Reg(8, 4), Op::Reg(0, 4), Op::Reg(16, 4)],
    ),
    f(
        "pkhtb",
        Set::T32,
        0xeac00020,
        true,
        &[
            Op::Reg(8, 4),
            Op::Reg(16, 4),
            Op::Reg(0, 4),
            Op::SatShift(6, 2, 255, 12, 3),
        ],
    ),
    f(
        "pkhtb",
        Set::Arm,
        0x06800010,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4), Op::Reg(16, 4)],
    ),
    f(
        "pkhtb",
        Set::Arm,
        0x06800050,
        true,
        &[
            Op::Reg(12, 4),
            Op::Reg(16, 4),
            Op::Reg(0, 4),
            Op::SatShift(7, 5, 255, 255, 0),
        ],
    ),
    f("pssbb", Set::T32, 0xf3bf8f44, false, &[]),
    f("pssbb", Set::Arm, 0xf57ff044, false, &[]),
    f(
        "qadd",
        Set::T32,
        0xfa80f080,
        true,
        &[Op::Reg(8, 4), Op::Reg(0, 4), Op::Reg(16, 4)],
    ),
    f(
        "qadd",
        Set::Arm,
        0x01000050,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4), Op::Reg(16, 4)],
    ),
    f(
        "qadd16",
        Set::T32,
        0xfa90f010,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "qadd16",
        Set::Arm,
        0x06200f10,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "qadd8",
        Set::T32,
        0xfa80f010,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "qadd8",
        Set::Arm,
        0x06200f90,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "qasx",
        Set::T32,
        0xfaa0f010,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "qasx",
        Set::Arm,
        0x06200f30,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "qdadd",
        Set::T32,
        0xfa80f090,
        true,
        &[Op::Reg(8, 4), Op::Reg(0, 4), Op::Reg(16, 4)],
    ),
    f(
        "qdadd",
        Set::Arm,
        0x01400050,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4), Op::Reg(16, 4)],
    ),
    f(
        "qdsub",
        Set::T32,
        0xfa80f0b0,
        true,
        &[Op::Reg(8, 4), Op::Reg(0, 4), Op::Reg(16, 4)],
    ),
    f(
        "qdsub",
        Set::Arm,
        0x01600050,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4), Op::Reg(16, 4)],
    ),
    f(
        "qsax",
        Set::T32,
        0xfae0f010,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "qsax",
        Set::Arm,
        0x06200f50,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "qsub",
        Set::T32,
        0xfa80f0a0,
        true,
        &[Op::Reg(8, 4), Op::Reg(0, 4), Op::Reg(16, 4)],
    ),
    f(
        "qsub",
        Set::Arm,
        0x01200050,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4), Op::Reg(16, 4)],
    ),
    f(
        "qsub16",
        Set::T32,
        0xfad0f010,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "qsub16",
        Set::Arm,
        0x06200f70,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "qsub8",
        Set::T32,
        0xfac0f010,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "qsub8",
        Set::Arm,
        0x06200ff0,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "rbit",
        Set::T32,
        0xfa90f0a0,
        true,
        &[Op::Reg(8, 4), Op::RegTwice(16, 0)],
    ),
    f(
        "rbit",
        Set::Arm,
        0x06ff0f30,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4)],
    ),
    f(
        "rev",
        Set::T16,
        0x0000ba00,
        true,
        &[Op::Reg(0, 3), Op::Reg(3, 3)],
    ),
    f(
        "rev",
        Set::T32,
        0xfa90f080,
        true,
        &[Op::Reg(8, 4), Op::RegTwice(16, 0)],
    ),
    f(
        "rev",
        Set::Arm,
        0x06bf0f30,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4)],
    ),
    f(
        "rev16",
        Set::T16,
        0x0000ba40,
        true,
        &[Op::Reg(0, 3), Op::Reg(3, 3)],
    ),
    f(
        "rev16",
        Set::T32,
        0xfa90f090,
        true,
        &[Op::Reg(8, 4), Op::RegTwice(16, 0)],
    ),
    f(
        "rev16",
        Set::Arm,
        0x06bf0fb0,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4)],
    ),
    f(
        "revsh",
        Set::T16,
        0x0000bac0,
        true,
        &[Op::Reg(0, 3), Op::Reg(3, 3)],
    ),
    f(
        "revsh",
        Set::T32,
        0xfa90f0b0,
        true,
        &[Op::Reg(8, 4), Op::RegTwice(16, 0)],
    ),
    f(
        "revsh",
        Set::Arm,
        0x06ff0fb0,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4)],
    ),
    f(
        "rfeda",
        Set::Arm,
        0xf8100a00,
        false,
        &[Op::Reg(16, 4), Op::Writeback(21)],
    ),
    f(
        "rfedb",
        Set::T32,
        0xe810c000,
        true,
        &[Op::Reg(16, 4), Op::Writeback(21)],
    ),
    f(
        "rfedb",
        Set::Arm,
        0xf9100a00,
        false,
        &[Op::Reg(16, 4), Op::Writeback(21)],
    ),
    f(
        "rfeia",
        Set::T32,
        0xe990c000,
        true,
        &[Op::Reg(16, 4), Op::Writeback(21)],
    ),
    f(
        "rfeia",
        Set::Arm,
        0xf8900a00,
        false,
        &[Op::Reg(16, 4), Op::Writeback(21)],
    ),
    f(
        "rfeib",
        Set::Arm,
        0xf9900a00,
        false,
        &[Op::Reg(16, 4), Op::Writeback(21)],
    ),
    f(
        "sadd16",
        Set::T32,
        0xfa90f000,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "sadd16",
        Set::Arm,
        0x06100f10,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "sadd8",
        Set::T32,
        0xfa80f000,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "sadd8",
        Set::Arm,
        0x06100f90,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "sasx",
        Set::T32,
        0xfaa0f000,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "sasx",
        Set::Arm,
        0x06100f30,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "sbfx",
        Set::T32,
        0xf3400000,
        true,
        &[
            Op::Reg(8, 4),
            Op::Reg(16, 4),
            Op::Lsb(&[(6, 2), (12, 3)]),
            Op::Width(&[(0, 5)]),
        ],
    ),
    f(
        "sbfx",
        Set::Arm,
        0x07a00050,
        true,
        &[
            Op::Reg(12, 4),
            Op::Reg(0, 4),
            Op::Imm(&[(7, 5)], 1, 0),
            Op::Imm(&[(16, 5)], 1, 1),
        ],
    ),
    f(
        "sdiv",
        Set::T32,
        0xfb90f0f0,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "sdiv",
        Set::Arm,
        0x0710f010,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "sel",
        Set::T32,
        0xfaa0f080,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "sel",
        Set::Arm,
        0x06800fb0,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f("setend", Set::T16, 0x0000b650, false, &[Op::Endian(3)]),
    f("setend", Set::Arm, 0xf1010000, false, &[Op::Endian(9)]),
    f("sev", Set::T16, 0x0000bf40, true, &[]),
    f("sev", Set::T32, 0xf3af8004, true, &[]),
    f("sev", Set::Arm, 0x0320f004, true, &[]),
    f(
        "shadd16",
        Set::T32,
        0xfa90f020,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "shadd16",
        Set::Arm,
        0x06300f10,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "shadd8",
        Set::T32,
        0xfa80f020,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "shadd8",
        Set::Arm,
        0x06300f90,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "shasx",
        Set::T32,
        0xfaa0f020,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "shasx",
        Set::Arm,
        0x06300f30,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "shsax",
        Set::T32,
        0xfae0f020,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "shsax",
        Set::Arm,
        0x06300f50,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "shsub16",
        Set::T32,
        0xfad0f020,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "shsub16",
        Set::Arm,
        0x06300f70,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "shsub8",
        Set::T32,
        0xfac0f020,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "shsub8",
        Set::Arm,
        0x06300ff0,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smc",
        Set::T32,
        0xf7f08000,
        true,
        &[Op::Imm(&[(16, 4)], 1, 0)],
    ),
    f(
        "smc",
        Set::Arm,
        0x01600070,
        true,
        &[Op::Imm(&[(0, 4)], 1, 0)],
    ),
    f(
        "smlabb",
        Set::T32,
        0xfb100000,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(12, 4)],
    ),
    f(
        "smlabb",
        Set::Arm,
        0x01000080,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4), Op::Reg(12, 4)],
    ),
    f(
        "smlabt",
        Set::T32,
        0xfb100010,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(12, 4)],
    ),
    f(
        "smlabt",
        Set::Arm,
        0x010000c0,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4), Op::Reg(12, 4)],
    ),
    f(
        "smlad",
        Set::T32,
        0xfb200000,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(12, 4)],
    ),
    f(
        "smlad",
        Set::Arm,
        0x07000010,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4), Op::Reg(12, 4)],
    ),
    f(
        "smladx",
        Set::T32,
        0xfb200010,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(12, 4)],
    ),
    f(
        "smladx",
        Set::Arm,
        0x07000030,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4), Op::Reg(12, 4)],
    ),
    f(
        "smlalbb",
        Set::T32,
        0xfbc00080,
        true,
        &[Op::Reg(12, 4), Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smlalbb",
        Set::Arm,
        0x01400080,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "smlalbt",
        Set::T32,
        0xfbc00090,
        true,
        &[Op::Reg(12, 4), Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smlalbt",
        Set::Arm,
        0x014000c0,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "smlald",
        Set::T32,
        0xfbc000c0,
        true,
        &[Op::Reg(12, 4), Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smlald",
        Set::Arm,
        0x07400010,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "smlaldx",
        Set::T32,
        0xfbc000d0,
        true,
        &[Op::Reg(12, 4), Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smlaldx",
        Set::Arm,
        0x07400030,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "smlaltb",
        Set::T32,
        0xfbc000a0,
        true,
        &[Op::Reg(12, 4), Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smlaltb",
        Set::Arm,
        0x014000a0,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "smlaltt",
        Set::T32,
        0xfbc000b0,
        true,
        &[Op::Reg(12, 4), Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smlaltt",
        Set::Arm,
        0x014000e0,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "smlatb",
        Set::T32,
        0xfb100020,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(12, 4)],
    ),
    f(
        "smlatb",
        Set::Arm,
        0x010000a0,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4), Op::Reg(12, 4)],
    ),
    f(
        "smlatt",
        Set::T32,
        0xfb100030,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(12, 4)],
    ),
    f(
        "smlatt",
        Set::Arm,
        0x010000e0,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4), Op::Reg(12, 4)],
    ),
    f(
        "smlawb",
        Set::T32,
        0xfb300000,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(12, 4)],
    ),
    f(
        "smlawb",
        Set::Arm,
        0x01200080,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4), Op::Reg(12, 4)],
    ),
    f(
        "smlawt",
        Set::T32,
        0xfb300010,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(12, 4)],
    ),
    f(
        "smlawt",
        Set::Arm,
        0x012000c0,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4), Op::Reg(12, 4)],
    ),
    f(
        "smlsd",
        Set::T32,
        0xfb400000,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(12, 4)],
    ),
    f(
        "smlsd",
        Set::Arm,
        0x07000050,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4), Op::Reg(12, 4)],
    ),
    f(
        "smlsdx",
        Set::T32,
        0xfb400010,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(12, 4)],
    ),
    f(
        "smlsdx",
        Set::Arm,
        0x07000070,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4), Op::Reg(12, 4)],
    ),
    f(
        "smlsld",
        Set::T32,
        0xfbd000c0,
        true,
        &[Op::Reg(12, 4), Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smlsld",
        Set::Arm,
        0x07400050,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "smlsldx",
        Set::T32,
        0xfbd000d0,
        true,
        &[Op::Reg(12, 4), Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smlsldx",
        Set::Arm,
        0x07400070,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "smmla",
        Set::T32,
        0xfb500000,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(12, 4)],
    ),
    f(
        "smmla",
        Set::Arm,
        0x07500010,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4), Op::Reg(12, 4)],
    ),
    f(
        "smmlar",
        Set::T32,
        0xfb500010,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(12, 4)],
    ),
    f(
        "smmlar",
        Set::Arm,
        0x07500030,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4), Op::Reg(12, 4)],
    ),
    f(
        "smmls",
        Set::T32,
        0xfb600000,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(12, 4)],
    ),
    f(
        "smmls",
        Set::Arm,
        0x075000d0,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4), Op::Reg(12, 4)],
    ),
    f(
        "smmlsr",
        Set::T32,
        0xfb600010,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(12, 4)],
    ),
    f(
        "smmlsr",
        Set::Arm,
        0x075000f0,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4), Op::Reg(12, 4)],
    ),
    f(
        "smmul",
        Set::T32,
        0xfb50f000,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smmul",
        Set::Arm,
        0x0750f010,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "smmulr",
        Set::T32,
        0xfb50f010,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smmulr",
        Set::Arm,
        0x0750f030,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "smuad",
        Set::T32,
        0xfb20f000,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smuad",
        Set::Arm,
        0x0700f010,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "smuadx",
        Set::T32,
        0xfb20f010,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smuadx",
        Set::Arm,
        0x0700f030,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "smulbb",
        Set::T32,
        0xfb10f000,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smulbb",
        Set::Arm,
        0x01600080,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "smulbt",
        Set::T32,
        0xfb10f010,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smulbt",
        Set::Arm,
        0x016000c0,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "smultb",
        Set::T32,
        0xfb10f020,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smultb",
        Set::Arm,
        0x016000a0,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "smultt",
        Set::T32,
        0xfb10f030,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smultt",
        Set::Arm,
        0x016000e0,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "smulwb",
        Set::T32,
        0xfb30f000,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smulwb",
        Set::Arm,
        0x012000a0,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "smulwt",
        Set::T32,
        0xfb30f010,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smulwt",
        Set::Arm,
        0x012000e0,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "smusd",
        Set::T32,
        0xfb40f000,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smusd",
        Set::Arm,
        0x0700f050,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "smusdx",
        Set::T32,
        0xfb40f010,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "smusdx",
        Set::Arm,
        0x0700f070,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "srsda",
        Set::Arm,
        0xf84d0500,
        false,
        &[Op::SpBase(16, 21), Op::Imm(&[(0, 5)], 1, 0)],
    ),
    f(
        "srsdb",
        Set::T32,
        0xe800c000,
        true,
        &[Op::SpBase(16, 21), Op::Imm(&[(0, 5)], 1, 0)],
    ),
    f(
        "srsdb",
        Set::Arm,
        0xf94d0500,
        false,
        &[Op::SpBase(16, 21), Op::Imm(&[(0, 5)], 1, 0)],
    ),
    f(
        "srsia",
        Set::T32,
        0xe980c000,
        true,
        &[Op::SpBase(16, 21), Op::Imm(&[(0, 5)], 1, 0)],
    ),
    f(
        "srsia",
        Set::Arm,
        0xf8cd0500,
        false,
        &[Op::SpBase(16, 21), Op::Imm(&[(0, 5)], 1, 0)],
    ),
    f(
        "srsib",
        Set::Arm,
        0xf9cd0500,
        false,
        &[Op::SpBase(16, 21), Op::Imm(&[(0, 5)], 1, 0)],
    ),
    f(
        "ssat",
        Set::T32,
        0xf3000000,
        true,
        &[
            Op::Reg(8, 4),
            Op::Imm(&[(0, 5)], 1, 1),
            Op::Reg(16, 4),
            Op::SatShift(6, 2, 21, 12, 3),
        ],
    ),
    f(
        "ssat",
        Set::Arm,
        0x06a00010,
        true,
        &[
            Op::Reg(12, 4),
            Op::Imm(&[(16, 5)], 1, 1),
            Op::Reg(0, 4),
            Op::SatShift(7, 5, 6, 255, 0),
        ],
    ),
    f(
        "ssat16",
        Set::T32,
        0xf3200000,
        true,
        &[Op::Reg(8, 4), Op::Imm(&[(0, 5)], 1, 1), Op::Reg(16, 4)],
    ),
    f(
        "ssat16",
        Set::Arm,
        0x06a00f30,
        true,
        &[Op::Reg(12, 4), Op::Imm(&[(16, 4)], 1, 1), Op::Reg(0, 4)],
    ),
    f(
        "ssax",
        Set::T32,
        0xfae0f000,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "ssax",
        Set::Arm,
        0x06100f50,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f("ssbb", Set::T32, 0xf3bf8f40, false, &[]),
    f("ssbb", Set::Arm, 0xf57ff040, false, &[]),
    f(
        "ssub16",
        Set::T32,
        0xfad0f000,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "ssub16",
        Set::Arm,
        0x06100f70,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "ssub8",
        Set::T32,
        0xfac0f000,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "ssub8",
        Set::Arm,
        0x06100ff0,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "stc",
        Set::T32,
        0xec000000,
        false,
        &[Op::Coproc(8), Op::CReg(12), Op::CoprocMem],
    ),
    f(
        "stc",
        Set::Arm,
        0x0c000000,
        true,
        &[Op::Coproc(8), Op::CReg(12), Op::CoprocMem],
    ),
    f(
        "stc2",
        Set::T32,
        0xfc000000,
        false,
        &[Op::Coproc(8), Op::CReg(12), Op::CoprocMem],
    ),
    f(
        "stc2",
        Set::Arm,
        0xfc000000,
        true,
        &[Op::Coproc(8), Op::CReg(12), Op::CoprocMem],
    ),
    f(
        "stc2l",
        Set::T32,
        0xfc400000,
        false,
        &[Op::Coproc(8), Op::CReg(12), Op::CoprocMem],
    ),
    f(
        "stc2l",
        Set::Arm,
        0xfc400000,
        true,
        &[Op::Coproc(8), Op::CReg(12), Op::CoprocMem],
    ),
    f(
        "stcl",
        Set::T32,
        0xec400000,
        false,
        &[Op::Coproc(8), Op::CReg(12), Op::CoprocMem],
    ),
    f(
        "stcl",
        Set::Arm,
        0x0c400000,
        true,
        &[Op::Coproc(8), Op::CReg(12), Op::CoprocMem],
    ),
    f(
        "strex",
        Set::T32,
        0xe8400000,
        true,
        &[Op::Reg(8, 4), Op::Reg(12, 4), Op::Base(16, 4)],
    ),
    f(
        "strex",
        Set::T32,
        0xe8400000,
        true,
        &[Op::Reg(8, 4), Op::Reg(12, 4), Op::OffMem(16, &[(0, 8)], 4)],
    ),
    f(
        "strex",
        Set::Arm,
        0x01800f90,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4), Op::Base(16, 4)],
    ),
    f(
        "strexb",
        Set::T32,
        0xe8c00f40,
        true,
        &[Op::Reg(0, 4), Op::Reg(12, 4), Op::Base(16, 4)],
    ),
    f(
        "strexb",
        Set::Arm,
        0x01c00f90,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4), Op::Base(16, 4)],
    ),
    f(
        "strexd",
        Set::T32,
        0xe8c00070,
        true,
        &[
            Op::Reg(0, 4),
            Op::Reg(12, 4),
            Op::Reg(8, 4),
            Op::Base(16, 4),
        ],
    ),
    f(
        "strexd",
        Set::Arm,
        0x01a00f90,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4), Op::Next, Op::Base(16, 4)],
    ),
    f(
        "strexh",
        Set::T32,
        0xe8c00f50,
        true,
        &[Op::Reg(0, 4), Op::Reg(12, 4), Op::Base(16, 4)],
    ),
    f(
        "strexh",
        Set::Arm,
        0x01e00f90,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4), Op::Base(16, 4)],
    ),
    f(
        "svc",
        Set::T16,
        0x0000df00,
        true,
        &[Op::Imm(&[(0, 8)], 1, 0)],
    ),
    f(
        "svc",
        Set::Arm,
        0x0f000000,
        true,
        &[Op::Imm(&[(0, 24)], 1, 0)],
    ),
    f(
        "swp",
        Set::Arm,
        0x01000090,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4), Op::Base(16, 4)],
    ),
    f(
        "swpb",
        Set::Arm,
        0x01400090,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4), Op::Base(16, 4)],
    ),
    f(
        "sxtab",
        Set::T32,
        0xfa40f080,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Rotate(4)],
    ),
    f(
        "sxtab",
        Set::Arm,
        0x06a00070,
        true,
        &[
            Op::Reg(12, 4),
            Op::Reg(16, 4),
            Op::Reg(0, 4),
            Op::Rotate(10),
        ],
    ),
    f(
        "sxtab16",
        Set::T32,
        0xfa20f080,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Rotate(4)],
    ),
    f(
        "sxtab16",
        Set::Arm,
        0x06800070,
        true,
        &[
            Op::Reg(12, 4),
            Op::Reg(16, 4),
            Op::Reg(0, 4),
            Op::Rotate(10),
        ],
    ),
    f(
        "sxtah",
        Set::T32,
        0xfa00f080,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Rotate(4)],
    ),
    f(
        "sxtah",
        Set::Arm,
        0x06b00070,
        true,
        &[
            Op::Reg(12, 4),
            Op::Reg(16, 4),
            Op::Reg(0, 4),
            Op::Rotate(10),
        ],
    ),
    f(
        "sxtb",
        Set::T16,
        0x0000b240,
        true,
        &[Op::Reg(0, 3), Op::Reg(3, 3)],
    ),
    f(
        "sxtb",
        Set::T32,
        0xfa4ff080,
        true,
        &[Op::Reg(8, 4), Op::Reg(0, 4), Op::Rotate(4)],
    ),
    f(
        "sxtb",
        Set::Arm,
        0x06af0070,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4), Op::Rotate(10)],
    ),
    f(
        "sxtb16",
        Set::T32,
        0xfa2ff080,
        true,
        &[Op::Reg(8, 4), Op::Reg(0, 4), Op::Rotate(4)],
    ),
    f(
        "sxtb16",
        Set::Arm,
        0x068f0070,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4), Op::Rotate(10)],
    ),
    f(
        "sxth",
        Set::T16,
        0x0000b200,
        true,
        &[Op::Reg(0, 3), Op::Reg(3, 3)],
    ),
    f(
        "sxth",
        Set::T32,
        0xfa0ff080,
        true,
        &[Op::Reg(8, 4), Op::Reg(0, 4), Op::Rotate(4)],
    ),
    f(
        "sxth",
        Set::Arm,
        0x06bf0070,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4), Op::Rotate(10)],
    ),
    f("tbb", Set::T32, 0xe8d0f000, true, &[Op::IdxMem(16, 0, 0)]),
    f("tbh", Set::T32, 0xe8d0f010, true, &[Op::IdxMem(16, 0, 1)]),
    f(
        "uadd16",
        Set::T32,
        0xfa90f040,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uadd16",
        Set::Arm,
        0x06500f10,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uadd8",
        Set::T32,
        0xfa80f040,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uadd8",
        Set::Arm,
        0x06500f90,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uasx",
        Set::T32,
        0xfaa0f040,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uasx",
        Set::Arm,
        0x06500f30,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "ubfx",
        Set::T32,
        0xf3c00000,
        true,
        &[
            Op::Reg(8, 4),
            Op::Reg(16, 4),
            Op::Lsb(&[(6, 2), (12, 3)]),
            Op::Width(&[(0, 5)]),
        ],
    ),
    f(
        "ubfx",
        Set::Arm,
        0x07e00050,
        true,
        &[
            Op::Reg(12, 4),
            Op::Reg(0, 4),
            Op::Imm(&[(7, 5)], 1, 0),
            Op::Imm(&[(16, 5)], 1, 1),
        ],
    ),
    f(
        "udf",
        Set::T16,
        0x0000de00,
        true,
        &[Op::Imm(&[(0, 8)], 1, 0)],
    ),
    f(
        "udf",
        Set::T32,
        0xf7f0a000,
        true,
        &[Op::Imm(&[(0, 12), (16, 4)], 1, 0)],
    ),
    f(
        "udf",
        Set::Arm,
        0xe7f000f0,
        false,
        &[Op::Imm(&[(0, 4), (8, 12)], 1, 0)],
    ),
    f(
        "udiv",
        Set::T32,
        0xfbb0f0f0,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "udiv",
        Set::Arm,
        0x0730f010,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "uhadd16",
        Set::T32,
        0xfa90f060,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uhadd16",
        Set::Arm,
        0x06700f10,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uhadd8",
        Set::T32,
        0xfa80f060,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uhadd8",
        Set::Arm,
        0x06700f90,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uhasx",
        Set::T32,
        0xfaa0f060,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uhasx",
        Set::Arm,
        0x06700f30,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uhsax",
        Set::T32,
        0xfae0f060,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uhsax",
        Set::Arm,
        0x06700f50,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uhsub16",
        Set::T32,
        0xfad0f060,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uhsub16",
        Set::Arm,
        0x06700f70,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uhsub8",
        Set::T32,
        0xfac0f060,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uhsub8",
        Set::Arm,
        0x06700ff0,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "umaal",
        Set::T32,
        0xfbe00060,
        true,
        &[Op::Reg(12, 4), Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "umaal",
        Set::Arm,
        0x00400090,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "undefined (bcc, cond=0xE)",
        Set::T32,
        0xf3808000,
        false,
        &[],
    ),
    f(
        "undefined (bcc, cond=0xF)",
        Set::T32,
        0xf3c08000,
        false,
        &[],
    ),
    f(
        "uqadd16",
        Set::T32,
        0xfa90f050,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uqadd16",
        Set::Arm,
        0x06600f10,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uqadd8",
        Set::T32,
        0xfa80f050,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uqadd8",
        Set::Arm,
        0x06600f90,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uqasx",
        Set::T32,
        0xfaa0f050,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uqasx",
        Set::Arm,
        0x06600f30,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uqsax",
        Set::T32,
        0xfae0f050,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uqsax",
        Set::Arm,
        0x06600f50,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uqsub16",
        Set::T32,
        0xfad0f050,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uqsub16",
        Set::Arm,
        0x06600f70,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uqsub8",
        Set::T32,
        0xfac0f050,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uqsub8",
        Set::Arm,
        0x06600ff0,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "usad8",
        Set::T32,
        0xfb70f000,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "usad8",
        Set::Arm,
        0x0780f010,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4)],
    ),
    f(
        "usada8",
        Set::T32,
        0xfb700000,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(12, 4)],
    ),
    f(
        "usada8",
        Set::Arm,
        0x07800010,
        true,
        &[Op::Reg(16, 4), Op::Reg(0, 4), Op::Reg(8, 4), Op::Reg(12, 4)],
    ),
    f(
        "usat",
        Set::T32,
        0xf3800000,
        true,
        &[
            Op::Reg(8, 4),
            Op::Imm(&[(0, 5)], 1, 0),
            Op::Reg(16, 4),
            Op::SatShift(6, 2, 21, 12, 3),
        ],
    ),
    f(
        "usat",
        Set::Arm,
        0x06e00010,
        true,
        &[
            Op::Reg(12, 4),
            Op::Imm(&[(16, 5)], 1, 0),
            Op::Reg(0, 4),
            Op::SatShift(7, 5, 6, 255, 0),
        ],
    ),
    f(
        "usat16",
        Set::T32,
        0xf3a00000,
        true,
        &[Op::Reg(8, 4), Op::Imm(&[(0, 5)], 1, 0), Op::Reg(16, 4)],
    ),
    f(
        "usat16",
        Set::Arm,
        0x06e00f30,
        true,
        &[Op::Reg(12, 4), Op::Imm(&[(16, 4)], 1, 0), Op::Reg(0, 4)],
    ),
    f(
        "usax",
        Set::T32,
        0xfae0f040,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "usax",
        Set::Arm,
        0x06500f50,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "usub16",
        Set::T32,
        0xfad0f040,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "usub16",
        Set::Arm,
        0x06500f70,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "usub8",
        Set::T32,
        0xfac0f040,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "usub8",
        Set::Arm,
        0x06500ff0,
        true,
        &[Op::Reg(12, 4), Op::Reg(16, 4), Op::Reg(0, 4)],
    ),
    f(
        "uxtab",
        Set::T32,
        0xfa50f080,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Rotate(4)],
    ),
    f(
        "uxtab",
        Set::Arm,
        0x06e00070,
        true,
        &[
            Op::Reg(12, 4),
            Op::Reg(16, 4),
            Op::Reg(0, 4),
            Op::Rotate(10),
        ],
    ),
    f(
        "uxtab16",
        Set::T32,
        0xfa30f080,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Rotate(4)],
    ),
    f(
        "uxtab16",
        Set::Arm,
        0x06c00070,
        true,
        &[
            Op::Reg(12, 4),
            Op::Reg(16, 4),
            Op::Reg(0, 4),
            Op::Rotate(10),
        ],
    ),
    f(
        "uxtah",
        Set::T32,
        0xfa10f080,
        true,
        &[Op::Reg(8, 4), Op::Reg(16, 4), Op::Reg(0, 4), Op::Rotate(4)],
    ),
    f(
        "uxtah",
        Set::Arm,
        0x06f00070,
        true,
        &[
            Op::Reg(12, 4),
            Op::Reg(16, 4),
            Op::Reg(0, 4),
            Op::Rotate(10),
        ],
    ),
    f(
        "uxtb",
        Set::T16,
        0x0000b2c0,
        true,
        &[Op::Reg(0, 3), Op::Reg(3, 3)],
    ),
    f(
        "uxtb",
        Set::T32,
        0xfa5ff080,
        true,
        &[Op::Reg(8, 4), Op::Reg(0, 4), Op::Rotate(4)],
    ),
    f(
        "uxtb",
        Set::Arm,
        0x06ef0070,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4), Op::Rotate(10)],
    ),
    f(
        "uxtb16",
        Set::T32,
        0xfa3ff080,
        true,
        &[Op::Reg(8, 4), Op::Reg(0, 4), Op::Rotate(4)],
    ),
    f(
        "uxtb16",
        Set::Arm,
        0x06cf0070,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4), Op::Rotate(10)],
    ),
    f(
        "uxth",
        Set::T16,
        0x0000b280,
        true,
        &[Op::Reg(0, 3), Op::Reg(3, 3)],
    ),
    f(
        "uxth",
        Set::T32,
        0xfa1ff080,
        true,
        &[Op::Reg(8, 4), Op::Reg(0, 4), Op::Rotate(4)],
    ),
    f(
        "uxth",
        Set::Arm,
        0x06ff0070,
        true,
        &[Op::Reg(12, 4), Op::Reg(0, 4), Op::Rotate(10)],
    ),
    f("wfe", Set::T16, 0x0000bf20, true, &[]),
    f("wfe", Set::T32, 0xf3af8002, true, &[]),
    f("wfe", Set::Arm, 0x0320f002, true, &[]),
    f("wfi", Set::T16, 0x0000bf30, true, &[]),
    f("wfi", Set::T32, 0xf3af8003, true, &[]),
    f("wfi", Set::Arm, 0x0320f003, true, &[]),
    f("yield", Set::T16, 0x0000bf10, true, &[]),
    f("yield", Set::T32, 0xf3af8001, true, &[]),
    f("yield", Set::Arm, 0x0320f001, true, &[]),
];
