#!/bin/bash
# Regenerates the <target>-compiler.txt corpora of tools/coff-diff from
# tools/dwarf-diff/compiler.c: what Clang writes for Windows, which is what
# COFF objects are mostly assembled from in practice.
#
#   tools/coff-diff/compiler.sh
#
# The committed corpora came from Clang 22.1 at -O0 and -O2, for
# x86_64-windows-msvc and i686-windows-msvc. Another version writes other
# code, which is fine: the harness compares rsasm with llvm-mc on whatever the
# corpus holds.
#
# Two things are asked of Clang or edited out first, where the object would
# need something rsasm does not do, and both assemblers then read the same
# file:
#
# - `-fno-addrsig`, since the `.llvm_addrsig` table lists symbols by their
#   index in the symbol table, which no directive names;
# - the `@feat.00` symbol, whose `.def` block and `.globl` Clang writes with
#   the name unquoted but whose definition only llvm-mc's own name rules
#   accept. It is a flag for the linker's SAFESEH and control flow guard
#   checks, set in the file the corpus comes from.
#
# ARM64 is left out: Clang's ARM64 objects carry unwind data from ARM64's own
# `.seh_*` directives, which rsasm does not write.
set -u
here=$(cd "$(dirname "$0")" && pwd)
src="$here/../dwarf-diff/compiler.c"

command -v clang > /dev/null || { echo "clang not found" >&2; exit 1; }

for target in x86-64:x86_64 i386:i686; do
  name=${target%%:*}
  triple=${target#*:}-windows-msvc
  out="$here/$name-compiler.txt"
  {
    echo "# Generated by tools/coff-diff/compiler.sh from tools/dwarf-diff/compiler.c."
    for opt in -O0 -O2; do
      echo "=== clang $opt"
      clang --target="$triple" $opt -fno-addrsig -S -o - "$src" |
        awk '/\.def[ \t]+@feat\.00/ { skip = 1 } !skip && !/@feat\.00/ { print } skip && /\.endef/ { skip = 0 }'
    done
  } > "$out"
  echo "wrote $out"
done
